In [8]:
import pandas as pd
import numpy as np

In [9]:
def max_aggregate_df(df: pd.DataFrame, aggregate_col: str, max_col: str):    
    max_df = None

    cols = list(df.columns)

    for val in df[aggregate_col].unique():

        curr_df_raw = df.loc[df[aggregate_col] == val]

        max_value = curr_df_raw[max_col].max()

        curr_df = curr_df_raw.loc[curr_df_raw[max_col] == max_value]

        curr_df = pd.DataFrame({col: [','.join(list([str(_) for _ in curr_df[col].unique()]))] for col in cols})

        if max_df is None:
            max_df = curr_df
            continue

        max_df = pd.concat((max_df, curr_df), ignore_index=True)

    return max_df

In [10]:
raw_df = pd.read_csv('./module_comparison.csv')
raw_df.head()

,rna_seq_mod,rna_seq_overlap_fraction,microarray_mod,microarray_overlap_fraction
0,711,0.0,628,0.0
1,711,0.0,627,0.0
2,711,0.0,626,0.0
3,711,0.0,625,0.0
4,711,0.0,624,0.0

In [11]:
rna_seq_df = max_aggregate_df(raw_df, 'rna_seq_mod', 'rna_seq_overlap_fraction')

In [12]:
rna_seq_df['rna_seq_overlap_fraction'] = pd.to_numeric(rna_seq_df['rna_seq_overlap_fraction'], errors='coerce')
rna_seq_df.sort_values(by='rna_seq_overlap_fraction', ascending=False)

,rna_seq_mod,rna_seq_overlap_fraction,microarray_mod,microarray_overlap_fraction
366,345,0.483871,526,0.2112676056338028
507,204,0.423077,150,0.6111111111111112
308,403,0.361702,616,0.1827956989247312
695,16,0.333333,494,0.1212121212121212
487,224,0.333333,"233,110,64","0.0526315789473684,0.0625,0.0344827586206896"
...,...,...,...,...
427,284,0.022222,"628,599,578,535,496,481,475,474,430,414,409,40...","0.0526315789473684,0.0384615384615384,0.037037..."
461,250,0.022222,"600,594,591,590,585,583,579,577,543,540,522,52...","0.0192307692307692,0.0232558139534883,0.026315..."
186,525,0.022222,"601,555,544,511,422,384,373,349,348,313,301,29...","0.0333333333333333,0.04,0.0217391304347826,0.0..."
113,598,0.021739,"626,616,596,594,589,585,584,583,566,562,554,48...","0.037037037037037,0.010752688172043,0.04347826..."
153,558,0.019608,"586,584,500,474,418,409,401,399,386,365,356,35...","0.0185185185185185,0.032258064516129,0.0169491..."

In [13]:
microarray_df = max_aggregate_df(raw_df, 'microarray_mod', 'microarray_overlap_fraction')

In [14]:
microarray_df['microarray_overlap_fraction'] = pd.to_numeric(microarray_df['microarray_overlap_fraction'], errors='coerce')
microarray_df.sort_values(by='microarray_overlap_fraction', ascending=False)

,rna_seq_mod,rna_seq_overlap_fraction,microarray_mod,microarray_overlap_fraction
14,403,0.0851063829787234,614,1.000000
357,205,0.2857142857142857,271,0.666667
478,204,0.4230769230769231,150,0.611111
588,"640,202,165","0.0588235294117647,0.0256410256410256,0.023255...",40,0.333333
570,"267,161,110","0.0181818181818181,0.0344827586206896,0.022727...",58,0.333333
...,...,...,...,...
441,"703,660,654,633,618,617,564,558,489,483,482,47...","0.03125,0.0344827586206896,0.0232558139534883,...",187,0.022222
411,"662,633,616,610,602,592,567,559,508,503,498,49...","0.0232558139534883,0.0416666666666666,0.027027...",217,0.019608
421,"709,703,671,670,648,636,609,597,572,564,535,51...","0.04,0.03125,0.0196078431372549,0.028571428571...",207,0.017241
534,"701,658,602,592,556,528,526,522,507,503,480,45...","0.032258064516129,0.0217391304347826,0.03125,0...",94,0.015873
527,"703,660,654,625,602,579,564,559,554,537,522,51...","0.03125,0.0344827586206896,0.0232558139534883,...",101,0.014925