In [1]:
import pandas as pd
import sys

sys.path.append('../../')
from utils import clustering_utils

In [2]:
muco_exp = [
'TTHERM_00052190',
'TTHERM_00011710',
'TTHERM_00321680',
'TTHERM_00445920',
'TTHERM_00410180',
'THERM_00410210',
'TTHERM_00313130',
'TTHERM_00059370',
'TTHERM_00283800',
'TTHERM_00227750',
'TTHERM_00241790',
'TTHERM_00318900',
'TTHERM_00852790',
'TTHERM_00467390',
'TTHERM_01332070',
'TTHERM_00497590',
'TTHERM_00013410',
'TTHERM_00527180',
'TTHERM_00624730',
'TTHERM_00624720',
'TTHERM_00378890',
'TTHERM_00522600',
'TTHERM_01055600',
'TTHERM_00558350',
'TTHERM_00221120',
'TTHERM_00572100',
'TTHERM_00420770',
'TTHERM_00566910',
'TTHERM_00658810',
'TTHERM_00047330',
'TTHERM_000193469',
'TTHERM_000486279',
'TTHERM_00141040',
'TTHERM_00227750',
'TTHERM_00317390',
'TTHERM_00670750',
'TTHERM_01122800',
'TTHERM_01213910',
'TTHERM_00886960',
]

In [3]:
de_regranulation_df = pd.read_csv('de_regranulation_logFC_0.2_adj_P_Val_0.0005_B_1.csv')

In [4]:
de_muco = list(set(list(de_regranulation_df['Unnamed: 0'].values)).intersection(set(muco_exp)))
de = list(set(list(de_regranulation_df['Unnamed: 0'].values)) - set(muco_exp))
muco = list(set(muco_exp) - set(list(de_regranulation_df['Unnamed: 0'].values)))

In [5]:
de_regranulation_annot_df = pd.DataFrame({
    'TTHERM_ID': de_muco + de + muco,
    'mucocysts': ['DE,EV' for _ in range(len(de_muco))] + ['DE' for _ in range(len(de))] + ['EV' for _ in range(len(muco))],
    })

In [6]:
de_regranulation_annot_df

             TTHERM_ID mucocysts
0      TTHERM_00141040     DE,EV
1      TTHERM_01213910     DE,EV
2      TTHERM_00321680     DE,EV
3      TTHERM_00241790     DE,EV
4      TTHERM_00013410     DE,EV
...                ...       ...
1966   TTHERM_00378890        EV
1967   TTHERM_00221120        EV
1968  TTHERM_000193469        EV
1969   TTHERM_00624720        EV
1970   TTHERM_00624730        EV

[1971 rows x 2 columns]

In [7]:
modified_annotation = pd.read_csv('../../active_files/complete_annotation.csv')
modified_annotation_no_muco = modified_annotation.copy()

In [8]:
modified_annotation = modified_annotation.merge(de_regranulation_annot_df, on='TTHERM_ID', how='outer')
modified_annotation

,TTHERM_ID,seed_ortholog,evalue,score,eggNOG_OGs,max_annot_lvl,COG_category,Description,Preferred_name,GOs,...,KEGG_TC,CAZy,BiGG_Reaction,PFAMs,TGD2021_description,peptide,common_name,InterPro,InterPro_description,mucocysts
0,TTHERM_00840110,5911.EAS05042,0.0,1278.5,"2E5M0@1|root,2SCE9@2759|Eukaryota,3ZEBN@5878|C...",5878|Ciliophora,-,-,-,-,...,-,-,-,-,hypothetical protein,MISSNQTADQENKVENKVANAEHVNQQSYDSIPQSLSPAVIAQIMD...,Unnamed,-,-,NaN
1,TTHERM_01082930,31033.ENSTRUP00000031008,1.9999999999999997e-28,94.2,"COG5078@1|root,KOG0418@2759|Eukaryota,38KYZ@33...",33208|Metazoa,O,Belongs to the ubiquitin-conjugating enzyme fa...,UBE2K,"GO:0000209,GO:0003674,GO:0003824,GO:0004842,GO...",...,-,-,-,"UBA,UQ_con",ubiquitin-conjugating enzyme E2,MHKNILIILFQIFCCQIYTTIYTFYYFMANIVFIIHNVKLDLFSCF...,Unnamed,"IPR000608,IPR016135,IPR023313,IPR050113","Ubiquitin-conjugating enzyme E2,Ubiquitin-conj...",NaN
2,TTHERM_01081610,5911.EAR82090,0.0,2110.7,"2A5FX@1|root,2RY9I@2759|Eukaryota",2759|Eukaryota,-,-,-,-,...,-,-,-,PRESAN,transmembrane protein putative,MSSQSPAKLNNQNCAAANQYYNDLESCVQGYCIKQQSGSGARGCFP...,Unnamed,-,-,NaN
3,TTHERM_00059210,5911.EAR87408,3.2999999999999998e-298,983.9,"COG0575@1|root,KOG1440@2759|Eukaryota,3ZAR9@58...",5878|Ciliophora,I,Cytidylyltransferase family,-,-,...,-,-,-,CTP_transf_1,phosphatidate cytidylyltransferase,MSQVTNRSQKKSHQKRDEKSEEDSSDEKTDDFSEEELDKLQEAQKK...,Unnamed,"IPR000374,IPR016720","Phosphatidate cytidylyltransferase,Phosphatida...",NaN
4,TTHERM_00535200,5911.EAS03184,0.0,2448.3,"2E77S@1|root,2SDUU@2759|Eukaryota",5911.EAS03184|-,S,Src homology 3 domains,-,-,...,-,-,-,-,beta-Pak interactive eXchange factor Src-like ...,MFTKSNSRSALAGLNSIVNSQNDSLTSRAQHQNYAKKDLTISNSTS...,Unnamed,"IPR001452,IPR036028,IPR051569","SH3 domain,SH3-like domain superfamily,SH3 and...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26705,TTHERM_00013390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE
26706,TTHERM_00286891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE
26707,THERM_00410210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EV
26708,TTHERM_000486279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EV
26709,TTHERM_000193469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EV

In [9]:
modified_annotation.isna().sum()

TTHERM_ID                   0
seed_ortholog              23
evalue                     23
score                      23
eggNOG_OGs                 23
max_annot_lvl              23
COG_category               23
Description                23
Preferred_name             23
GOs                        23
EC                         23
KEGG_ko                    23
KEGG_Pathway               23
KEGG_Module                23
KEGG_Reaction              23
KEGG_rclass                23
BRITE                      23
KEGG_TC                    23
CAZy                       23
BiGG_Reaction              23
PFAMs                      23
TGD2021_description        23
peptide                    23
common_name                23
InterPro                   23
InterPro_description       23
mucocysts               24739
dtype: int64

In [10]:
modified_annotation = modified_annotation.fillna('-')

In [11]:
modified_annotation.isna().sum()

TTHERM_ID               0
seed_ortholog           0
evalue                  0
score                   0
eggNOG_OGs              0
max_annot_lvl           0
COG_category            0
Description             0
Preferred_name          0
GOs                     0
EC                      0
KEGG_ko                 0
KEGG_Pathway            0
KEGG_Module             0
KEGG_Reaction           0
KEGG_rclass             0
BRITE                   0
KEGG_TC                 0
CAZy                    0
BiGG_Reaction           0
PFAMs                   0
TGD2021_description     0
peptide                 0
common_name             0
InterPro                0
InterPro_description    0
mucocysts               0
dtype: int64

In [12]:
modified_annotation.to_csv('../../active_files/complete_annotation.csv', index=False)

In [13]:
veg = pd.read_csv('./veg_nn3_leiden_label_df_round_1.csv')

sex = pd.read_csv('./sex_nn3_leiden_label_df_round_1.csv')

In [14]:
veg_enrich = clustering_utils.compute_enrichment(veg)

sex_enrich = clustering_utils.compute_enrichment(sex)

In [15]:
modified_annotation_no_muco.to_csv('../../active_files/complete_annotation.csv', index=False)

In [16]:
veg_enrich.loc[veg_enrich['term'].isin(['DE,EV', 'EV'])]

,module,term,info,fold_change,bonferroni,term_count,module_size
0,549.0,EV,experimentally validated mucocyst-associated gene,585.745614,8.707998e-12,5.0,6.0
0,550.0,EV,experimentally validated mucocyst-associated gene,281.157895,5.698593e-03,2.0,5.0
1,551.0,EV,experimentally validated mucocyst-associated gene,135.172065,4.339311e-08,5.0,26.0
1,558.0,EV,experimentally validated mucocyst-associated gene,93.719298,4.666769e-09,6.0,45.0
1,560.0,EV,experimentally validated mucocyst-associated gene,58.574561,1.156786e-03,3.0,36.0
1,637.0,EV,experimentally validated mucocyst-associated gene,123.006579,1.739203e-11,7.0,40.0

In [17]:
sex_enrich.loc[sex_enrich['term'].isin(['DE,EV', 'EV'])]

,module,term,info,fold_change,bonferroni,term_count,module_size
1,572.0,EV,experimentally validated mucocyst-associated gene,37.655075,2.860730e-03,3.0,56.0
1,581.0,EV,experimentally validated mucocyst-associated gene,39.049708,2.657049e-03,3.0,54.0
1,583.0,EV,experimentally validated mucocyst-associated gene,133.884712,4.751839e-21,12.0,63.0
0,585.0,EV,experimentally validated mucocyst-associated gene,447.296651,5.738131e-16,7.0,11.0
0,617.0,EV,experimentally validated mucocyst-associated gene,45.348048,4.272690e-02,2.0,31.0

In [18]:
veg_ev_df = veg.loc[veg['label'].isin([int(m) for m in veg_enrich.loc[veg_enrich['term'].isin(['DE,EV', 'EV'])]['module'].values])]
sex_ev_df = sex.loc[sex['label'].isin([int(m) for m in sex_enrich.loc[sex_enrich['term'].isin(['DE,EV', 'EV'])]['module'].values])]

In [19]:
sex_veg_ev_df = sex.loc[sex['TTHERM_ID'].isin(veg_ev_df['TTHERM_ID'].values)]
veg_sex_ev_df = veg.loc[veg['TTHERM_ID'].isin(sex_ev_df['TTHERM_ID'].values)]

In [20]:
veg_ev_df = veg_ev_df.sort_values(by='TTHERM_ID')
sex_veg_ev_df = sex_veg_ev_df.sort_values(by='TTHERM_ID')

sex_ev_df = sex_ev_df.sort_values(by='TTHERM_ID')
veg_sex_ev_df = veg_sex_ev_df.sort_values(by='TTHERM_ID')

In [21]:
veg_ev_df

            TTHERM_ID  label
3562  TTHERM_00011710    558
3561  TTHERM_00013398    558
1201  TTHERM_00013410    637
3744  TTHERM_00016320    551
3743  TTHERM_00023880    551
...               ...    ...
3458  TTHERM_01256510    560
3457  TTHERM_01287970    560
3519  TTHERM_01321550    558
3518  TTHERM_01332070    558
1162  TTHERM_01372820    637

[158 rows x 2 columns]

In [22]:
sex_veg_ev_df

             TTHERM_ID  label
3167   TTHERM_00011710    583
17054  TTHERM_00013398    114
3166   TTHERM_00013410    583
4041   TTHERM_00016320    556
6036   TTHERM_00023880    487
...                ...    ...
2842   TTHERM_01256510    592
17138  TTHERM_01287970    110
3107   TTHERM_01321550    583
3106   TTHERM_01332070    583
3105   TTHERM_01372820    583

[158 rows x 2 columns]

In [36]:
# subset_labels_1 = veg_ev_df['label'].values
# subset_labels_2 = sex_veg_ev_df['label'].values

subset_labels_1 = sex_ev_df['label'].values
subset_labels_2 = veg_sex_ev_df['label'].values

In [37]:
len(veg_ev_df['label'].unique()), len(sex_veg_ev_df['label'].unique())

(6, 59)

In [38]:
len(sex_ev_df['label'].unique()), len(veg_sex_ev_df['label'].unique())

(5, 130)

In [39]:
print(*['m'+str(m).zfill(3) for m in veg_ev_df['label'].unique()], sep=', ')

m558, m637, m551, m550, m560, m549

In [40]:
print(*['m'+str(m).zfill(3) for m in sex_ev_df['label'].unique()], sep=', ')

m572, m617, m583, m581, m585

In [41]:
from sklearn.metrics import adjusted_rand_score, adjusted_mutual_info_score

# ARI
ari = adjusted_rand_score(subset_labels_1, subset_labels_2)
print(f"Adjusted Rand Index: {ari}")

# NMI
nmi = adjusted_mutual_info_score(subset_labels_1, subset_labels_2)
print(f"Normalized Mutual Information: {nmi}")

Adjusted Rand Index: 0.023320969600941065
Normalized Mutual Information: 0.06655247729457635

In [42]:
import pandas as pd
from scipy.stats import chi2_contingency

# Create a contingency table
contingency_table = pd.crosstab(subset_labels_1, subset_labels_2)

# Perform Chi-Square test
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-Square statistic: {chi2}, p-value: {p}")

Chi-Square statistic: 646.1893022336691, p-value: 8.003547236109321e-05

In [43]:
import pandas as pd

# Example contingency table
contingency_table = pd.crosstab(subset_labels_1, subset_labels_2)

# Find the maximum value in the contingency table
max_value = contingency_table.max().max()

# Find the coordinates (x and y axis labels) of the maximum value
max_coords = contingency_table.unstack().idxmax()

# Print the results
print(f"Maximum value: {max_value}")
print(f"x label: {max_coords[1]}")
print(f"y label: {max_coords[0]}")

Maximum value: 10
x label: 583
y label: 558

In [44]:
dof

516

In [50]:
v = ['TTHERM_01332070',
'TTHERM_01321550',
'TTHERM_01156770',
'TTHERM_01109815',
'TTHERM_01106040',
'TTHERM_01049340',
'TTHERM_00954170',
'TTHERM_00938950',
'TTHERM_00865220',
'TTHERM_00787390',
'TTHERM_00755930',
'TTHERM_00723030',
'TTHERM_00721270',
'TTHERM_00703870',
'TTHERM_00691410',
'TTHERM_00649480',
'TTHERM_00628650',
'TTHERM_00570550',
'TTHERM_00526730',
'TTHERM_00496990',
'TTHERM_00494700',
'TTHERM_00486995',
'TTHERM_00471470',
'TTHERM_00411560',
'TTHERM_00410180',
'TTHERM_00401970',
'TTHERM_00396455',
'TTHERM_00343930',
'TTHERM_00340010',
'TTHERM_00321720',
'TTHERM_00321680',
'TTHERM_00317390',
'TTHERM_00285430',
'TTHERM_00283760',
'TTHERM_00242080',
'TTHERM_00194310',
'TTHERM_00193465',
'TTHERM_00187110',
'TTHERM_00151905',
'TTHERM_00145430',
'TTHERM_00140780',
'TTHERM_00092820',
'TTHERM_00052190',
'TTHERM_00013398',
'TTHERM_00011710',
]

s = ['TTHERM_01372820',
'TTHERM_01332070',
'TTHERM_01321550',
'TTHERM_01245630',
'TTHERM_01197130',
'TTHERM_01165230',
'TTHERM_01156770',
'TTHERM_01100540',
'TTHERM_01078020',
'TTHERM_01071420',
'TTHERM_01044570',
'TTHERM_01027680',
'TTHERM_00967570',
'TTHERM_00938950',
'TTHERM_00850600',
'TTHERM_00780590',
'TTHERM_00733950',
'TTHERM_00721690',
'TTHERM_00721270',
'TTHERM_00686060',
'TTHERM_00685980',
'TTHERM_00672265',
'TTHERM_00592740',
'TTHERM_00586625',
'TTHERM_00579000',
'TTHERM_00554390',
'TTHERM_00538800',
'TTHERM_00532260',
'TTHERM_00526910',
'TTHERM_00526730',
'TTHERM_00522160',
'TTHERM_00516380',
'TTHERM_00497590',
'TTHERM_00486120',
'TTHERM_00445920',
'TTHERM_00440600',
'TTHERM_00410180',
'TTHERM_00409030',
'TTHERM_00390080',
'TTHERM_00361460',
'TTHERM_00355700',
'TTHERM_00321680',
'TTHERM_00314860',
'TTHERM_00313420',
'TTHERM_00310890',
'TTHERM_00285500',
'TTHERM_00283800',
'TTHERM_00241790',
'TTHERM_00220815',
'TTHERM_00197989',
'TTHERM_00194350',
'TTHERM_00185860',
'TTHERM_00170450',
'TTHERM_00145480',
'TTHERM_00141040',
'TTHERM_00114370',
'TTHERM_00094080',
'TTHERM_00082260',
'TTHERM_00052646',
'TTHERM_00052190',
'TTHERM_00047330',
'TTHERM_00013410',
'TTHERM_00011710',
]

print(*set(v).intersection(set(s)), sep=', ')

TTHERM_00052190, TTHERM_01321550, TTHERM_00011710, TTHERM_00526730, TTHERM_00321680, TTHERM_00721270, TTHERM_00938950, TTHERM_01156770, TTHERM_00410180, TTHERM_01332070

In [ ]:
list.sort()