In [1]:
import pandas as pd
from json import load

In [2]:
qc_rma_signal_data_df = pd.read_csv('../microarray_QC/QC_probe_rma_values.csv')
qc_rma_signal_data_df.head()

,Unnamed: 0,C0_GSM285570.xys,C0_GSM656230.xys,C10_GSM285578.xys,C10_GSM285591.xys,C12_GSM285579.xys,C12_GSM285592.xys,C12_GSM656237.xys,C14_GSM285580.xys,C14_GSM285593.xys,...,S3_GSM285542.xys,S3_GSM285555.xys,S3_GSM285562.xys,S6_GSM285543.xys,S6_GSM285556.xys,S6_GSM285563.xys,S9_GSM285544.xys,S9_GSM285564.xys,S9_GSM647653.xys,S9_GSM647654.xys
0,YF00000001.t1,4.611041,4.812746,4.361595,4.208651,4.188594,4.398242,4.588297,4.395502,4.348232,...,4.564301,4.776462,4.751153,4.613926,4.585880,4.953210,4.854646,4.926982,4.913556,4.471773
1,YF00000003.t1,13.189964,13.248510,10.952596,10.265773,10.118504,9.461205,11.513557,10.471010,9.960254,...,10.225865,10.113546,11.182089,11.222062,10.926224,10.622958,12.633820,12.213265,12.457502,12.379949
2,YF00000004.t1,12.560278,9.504713,12.929901,12.406680,11.763788,12.058028,9.835771,11.409396,11.766843,...,8.519833,8.348235,10.870517,7.434087,8.918464,8.191028,10.997769,9.292351,7.118309,6.979330
3,YF00000005.t1,6.347737,7.525253,7.085173,6.934692,6.685383,6.275538,7.076463,5.645302,5.691725,...,4.928717,5.258449,4.929858,4.791764,5.256188,5.119660,5.241866,5.359580,5.611715,5.183959
4,YF00000006.t1,12.698308,12.790263,12.856326,12.962115,12.531308,12.786629,12.149286,13.059034,12.736203,...,11.499305,11.820884,11.788514,11.863069,12.142037,12.086118,11.966577,12.092133,11.689686,11.966567

In [3]:
qc_rma_signal_data_df.rename(columns={'Unnamed: 0': 'TTHERM_ID'}, inplace=True)
qc_rma_signal_data_df.rename(columns={c: c.split('.')[0] for c in qc_rma_signal_data_df.columns}, inplace=True)
qc_rma_signal_data_df.head()

,TTHERM_ID,C0_GSM285570,C0_GSM656230,C10_GSM285578,C10_GSM285591,C12_GSM285579,C12_GSM285592,C12_GSM656237,C14_GSM285580,C14_GSM285593,...,S3_GSM285542,S3_GSM285555,S3_GSM285562,S6_GSM285543,S6_GSM285556,S6_GSM285563,S9_GSM285544,S9_GSM285564,S9_GSM647653,S9_GSM647654
0,YF00000001.t1,4.611041,4.812746,4.361595,4.208651,4.188594,4.398242,4.588297,4.395502,4.348232,...,4.564301,4.776462,4.751153,4.613926,4.585880,4.953210,4.854646,4.926982,4.913556,4.471773
1,YF00000003.t1,13.189964,13.248510,10.952596,10.265773,10.118504,9.461205,11.513557,10.471010,9.960254,...,10.225865,10.113546,11.182089,11.222062,10.926224,10.622958,12.633820,12.213265,12.457502,12.379949
2,YF00000004.t1,12.560278,9.504713,12.929901,12.406680,11.763788,12.058028,9.835771,11.409396,11.766843,...,8.519833,8.348235,10.870517,7.434087,8.918464,8.191028,10.997769,9.292351,7.118309,6.979330
3,YF00000005.t1,6.347737,7.525253,7.085173,6.934692,6.685383,6.275538,7.076463,5.645302,5.691725,...,4.928717,5.258449,4.929858,4.791764,5.256188,5.119660,5.241866,5.359580,5.611715,5.183959
4,YF00000006.t1,12.698308,12.790263,12.856326,12.962115,12.531308,12.786629,12.149286,13.059034,12.736203,...,11.499305,11.820884,11.788514,11.863069,12.142037,12.086118,11.966577,12.092133,11.689686,11.966567

In [4]:
len(qc_rma_signal_data_df['TTHERM_ID'].values)

22040

In [5]:
with open('../../new_raw_data/microarray_accessions_all.json', 'r') as f:
    # Including single REP measurement for C-15m (GSM656231) even though there are no replicates for it
    # in order to replicate the 2011 analysis
    # Format: keys are the physiological phase; values are the geo accessions for each microarray
    all_geo = load(f)
all_geo

{'Ll': ['GSM283687', 'GSM284355', 'GSM284362'],
 'Lm': ['GSM283690', 'GSM284357', 'GSM284363'],
 'Lh': ['GSM283691', 'GSM284360', 'GSM284364'],
 'S0': ['GSM285363',
  'GSM285554',
  'GSM285561',
  'GSM647244',
  'GSM647651',
  'GSM647652'],
 'S3': ['GSM285542', 'GSM285555', 'GSM285562'],
 'S6': ['GSM285543', 'GSM285556', 'GSM285563'],
 'S9': ['GSM285544', 'GSM285557', 'GSM285564', 'GSM647653', 'GSM647654'],
 'S12': ['GSM285545', 'GSM285558', 'GSM285565'],
 'S15': ['GSM285546', 'GSM285559', 'GSM285566'],
 'S24': ['GSM285547', 'GSM285560', 'GSM285567', 'GSM647245'],
 'C0': ['GSM285570', 'GSM285586', 'GSM656230'],
 'C15m': ['GSM656231'],
 'C2': ['GSM285572', 'GSM285587', 'GSM656233'],
 'C4': ['GSM285574', 'GSM285588', 'GSM656234'],
 'C6': ['GSM285575', 'GSM285589', 'GSM656232'],
 'C8': ['GSM285576', 'GSM285590', 'GSM656236'],
 'C10': ['GSM285578', 'GSM285591', 'GSM656235'],
 'C12': ['GSM285579', 'GSM285592', 'GSM656237'],
 'C14': ['GSM285580', 'GSM285593', 'GSM656238'],
 'C16': ['GSM285582', 'GSM285595', 'GSM656239'],
 'C18': ['GSM285583', 'GSM285596', 'GSM656240']}

In [6]:
col_names = []

for key in all_geo:
    for val in all_geo[key]:
        col_names.append(f'{key}_{val}')

In [7]:
ordered_columns = [c for c in col_names if c in qc_rma_signal_data_df.columns[1:]]
ordered_columns

['Ll_GSM283687',
 'Ll_GSM284355',
 'Ll_GSM284362',
 'Lm_GSM283690',
 'Lm_GSM284357',
 'Lm_GSM284363',
 'Lh_GSM283691',
 'Lh_GSM284360',
 'Lh_GSM284364',
 'S0_GSM285363',
 'S0_GSM285554',
 'S0_GSM285561',
 'S0_GSM647651',
 'S0_GSM647652',
 'S3_GSM285542',
 'S3_GSM285555',
 'S3_GSM285562',
 'S6_GSM285543',
 'S6_GSM285556',
 'S6_GSM285563',
 'S9_GSM285544',
 'S9_GSM285564',
 'S9_GSM647653',
 'S9_GSM647654',
 'S15_GSM285559',
 'S15_GSM285566',
 'S24_GSM285547',
 'S24_GSM285560',
 'C0_GSM285570',
 'C0_GSM656230',
 'C4_GSM285574',
 'C4_GSM285588',
 'C4_GSM656234',
 'C6_GSM285575',
 'C6_GSM656232',
 'C8_GSM285576',
 'C8_GSM285590',
 'C10_GSM285578',
 'C10_GSM285591',
 'C12_GSM285579',
 'C12_GSM285592',
 'C12_GSM656237',
 'C14_GSM285580',
 'C14_GSM285593',
 'C14_GSM656238',
 'C16_GSM285582',
 'C16_GSM285595',
 'C16_GSM656239',
 'C18_GSM285583',
 'C18_GSM285596',
 'C18_GSM656240']

In [8]:
tidy_column_order_list = ['TTHERM_ID'] + ordered_columns
tidy_column_order_list

['TTHERM_ID',
 'Ll_GSM283687',
 'Ll_GSM284355',
 'Ll_GSM284362',
 'Lm_GSM283690',
 'Lm_GSM284357',
 'Lm_GSM284363',
 'Lh_GSM283691',
 'Lh_GSM284360',
 'Lh_GSM284364',
 'S0_GSM285363',
 'S0_GSM285554',
 'S0_GSM285561',
 'S0_GSM647651',
 'S0_GSM647652',
 'S3_GSM285542',
 'S3_GSM285555',
 'S3_GSM285562',
 'S6_GSM285543',
 'S6_GSM285556',
 'S6_GSM285563',
 'S9_GSM285544',
 'S9_GSM285564',
 'S9_GSM647653',
 'S9_GSM647654',
 'S15_GSM285559',
 'S15_GSM285566',
 'S24_GSM285547',
 'S24_GSM285560',
 'C0_GSM285570',
 'C0_GSM656230',
 'C4_GSM285574',
 'C4_GSM285588',
 'C4_GSM656234',
 'C6_GSM285575',
 'C6_GSM656232',
 'C8_GSM285576',
 'C8_GSM285590',
 'C10_GSM285578',
 'C10_GSM285591',
 'C12_GSM285579',
 'C12_GSM285592',
 'C12_GSM656237',
 'C14_GSM285580',
 'C14_GSM285593',
 'C14_GSM656238',
 'C16_GSM285582',
 'C16_GSM285595',
 'C16_GSM656239',
 'C18_GSM285583',
 'C18_GSM285596',
 'C18_GSM656240']

In [9]:
len(tidy_column_order_list)

52

In [10]:
len(list(qc_rma_signal_data_df.columns))

52

In [11]:
tidy_qc_rma_signal_data_df = qc_rma_signal_data_df.loc[:,tidy_column_order_list]
tidy_qc_rma_signal_data_df.head()

,TTHERM_ID,Ll_GSM283687,Ll_GSM284355,Ll_GSM284362,Lm_GSM283690,Lm_GSM284357,Lm_GSM284363,Lh_GSM283691,Lh_GSM284360,Lh_GSM284364,...,C12_GSM656237,C14_GSM285580,C14_GSM285593,C14_GSM656238,C16_GSM285582,C16_GSM285595,C16_GSM656239,C18_GSM285583,C18_GSM285596,C18_GSM656240
0,YF00000001.t1,4.589101,4.658988,5.363515,4.826604,4.533779,5.008925,4.431251,4.801395,4.933612,...,4.588297,4.395502,4.348232,4.300153,4.487811,4.505757,4.598620,4.416853,4.694025,4.522450
1,YF00000003.t1,12.713124,13.122156,13.190829,12.795304,13.118586,13.032352,12.574914,12.663691,13.034661,...,11.513557,10.471010,9.960254,11.023613,11.673585,11.485081,11.210493,12.384087,12.286663,12.064307
2,YF00000004.t1,12.801491,13.816009,13.674157,12.359067,13.633952,13.615677,10.186907,12.650432,12.646102,...,9.835771,11.409396,11.766843,8.720915,11.643657,11.601037,7.363241,11.566631,11.881848,6.776089
3,YF00000005.t1,9.510123,10.560219,10.515640,9.734283,9.777910,10.445625,9.018961,9.359294,9.454292,...,7.076463,5.645302,5.691725,6.281886,5.106207,5.198772,6.182419,5.034927,5.121846,5.328239
4,YF00000006.t1,11.401541,11.656088,11.342039,10.903930,11.327460,11.285148,10.979501,11.088203,10.749591,...,12.149286,13.059034,12.736203,12.230047,12.797433,12.510993,12.813015,12.429498,12.418377,11.955661

In [12]:
tidy_qc_rma_signal_data_df.shape

(22040, 52)

In [13]:
duplicates = tidy_qc_rma_signal_data_df['TTHERM_ID'].duplicated()
tidy_qc_rma_signal_data_df[duplicates]

Empty DataFrame
Columns: [TTHERM_ID, Ll_GSM283687, Ll_GSM284355, Ll_GSM284362, Lm_GSM283690, Lm_GSM284357, Lm_GSM284363, Lh_GSM283691, Lh_GSM284360, Lh_GSM284364, S0_GSM285363, S0_GSM285554, S0_GSM285561, S0_GSM647651, S0_GSM647652, S3_GSM285542, S3_GSM285555, S3_GSM285562, S6_GSM285543, S6_GSM285556, S6_GSM285563, S9_GSM285544, S9_GSM285564, S9_GSM647653, S9_GSM647654, S15_GSM285559, S15_GSM285566, S24_GSM285547, S24_GSM285560, C0_GSM285570, C0_GSM656230, C4_GSM285574, C4_GSM285588, C4_GSM656234, C6_GSM285575, C6_GSM656232, C8_GSM285576, C8_GSM285590, C10_GSM285578, C10_GSM285591, C12_GSM285579, C12_GSM285592, C12_GSM656237, C14_GSM285580, C14_GSM285593, C14_GSM656238, C16_GSM285582, C16_GSM285595, C16_GSM656239, C18_GSM285583, C18_GSM285596, C18_GSM656240]
Index: []

[0 rows x 52 columns]

In [14]:
growth = ['Ll', 'Lm', 'Lh']
starvation = ['S0', 'S3', 'S6', 'S9', 'S12', 'S15', 'S24']
conjugation = ['C0', 'C15m', 'C2', 'C4', 'C6', 'C8', 'C10', 'C12', 'C14', 'C16', 'C18']
vegetative = growth + starvation

grow_cols = [c for c in tidy_qc_rma_signal_data_df.columns if c.split('_')[0] in growth]
starve_cols = [c for c in tidy_qc_rma_signal_data_df.columns if c.split('_')[0] in starvation]
sex_cols = [c for c in tidy_qc_rma_signal_data_df.columns if c.split('_')[0] in conjugation]
veg_cols = [c for c in tidy_qc_rma_signal_data_df.columns if c.split('_')[0] in vegetative]

In [15]:
tidy_qc_rma_signal_data_df_grow = tidy_qc_rma_signal_data_df[['TTHERM_ID'] + grow_cols]
tidy_qc_rma_signal_data_df_starve = tidy_qc_rma_signal_data_df[['TTHERM_ID'] + starve_cols]
tidy_qc_rma_signal_data_df_sex = tidy_qc_rma_signal_data_df[['TTHERM_ID'] + sex_cols]
tidy_qc_rma_signal_data_df_veg = tidy_qc_rma_signal_data_df[['TTHERM_ID'] + veg_cols]

In [16]:
tidy_qc_rma_signal_data_df.to_csv('./agg_tidy_2021aligned_qc_rma_expression_full.csv', index=False)
tidy_qc_rma_signal_data_df_grow.to_csv('./agg_tidy_2021aligned_qc_rma_expression_grow.csv', index=False)
tidy_qc_rma_signal_data_df_starve.to_csv('./agg_tidy_2021aligned_qc_rma_expression_starve.csv', index=False)
tidy_qc_rma_signal_data_df_veg.to_csv('./agg_tidy_2021aligned_qc_rma_expression_veg.csv', index=False)
tidy_qc_rma_signal_data_df_sex.to_csv('./agg_tidy_2021aligned_qc_rma_expression_sex.csv', index=False)